name:                NEAT
version:             0.1.0.0
github:              "qwfy/NEAT"
license:             MIT
author:              "Incomplete"
maintainer:          "incomplete@aixon.co"
copyright:           "Incomplete 2018"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/qwfy/NEAT#readme>

dependencies:
- base >= 4.7 && < 5
- uuid
- random
- containers
- stm
- vector

library:
  source-dirs: src

executables:
  neat:
    main:                NEAT.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NEAT
